[package]
name = "vrp-cli"
version = "1.4.3"
authors = ["Ilya Builuk <ilya.builuk@gmail.com>"]
license = "Apache-2.0"
keywords = ["vrp", "optimization"]
categories = ["algorithms", "science"]
readme = "../README.md"
homepage = "https://github.com/reinterpretcat/vrp"
repository = "https://github.com/reinterpretcat/vrp"
edition = "2018"
description = "A command line interface for VRP solver"

[lib]
name = "vrp_cli"
crate-type = ["cdylib", "lib"]

[dependencies]
vrp-core = { path = "../vrp-core", version = "1.4.3" }
vrp-scientific = { path = "../vrp-scientific", version = "1.4.3" }
vrp-pragmatic = { path = "../vrp-pragmatic", version = "1.4.3" }

csv = "1.1.3"
serde_json = "1.0.57"
serde = { version = "1.0.115", features = ["derive"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
clap = "2.33.3"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { version = "0.2.67", features = ["serde-serialize"] }
js-sys = "0.3.44"
