[package]
name = "vrp-cli"
version = "1.16.1"
authors = ["Ilya Builuk <ilya.builuk@gmail.com>"]
license = "Apache-2.0"
keywords = ["vrp", "optimization"]
categories = ["algorithms", "science"]
readme = "../README.md"
homepage = "https://github.com/reinterpretcat/vrp"
repository = "https://github.com/reinterpretcat/vrp"
edition = "2021"
description = "A command line interface for VRP solver"

[features]
default = ["csv-format", "scientific-format"]

csv-format = ["csv"]
scientific-format = ["vrp-scientific"]

[lib]
name = "vrp_cli"
crate-type = ["cdylib", "lib"]

[dependencies]
vrp-core = { path = "../vrp-core" }
vrp-scientific = { path = "../vrp-scientific", optional = true }
vrp-pragmatic = { path = "../vrp-pragmatic" }

csv = { version = "1.1.6", optional = true }
serde_json = "1.0.79"
serde = { version = "1.0.136", features = ["derive"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
clap = "3.1.6"
ctrlc = { version = "3.0", features = ["termination"] }
num_cpus = "1.13.1"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { version = "0.2.79", features = ["serde-serialize"] }
js-sys = "0.3.56"

[dev-dependencies]
tempfile = "3.3.0"
