[package]
name = "vrp-cli"
version = "1.9.1"
authors = ["Ilya Builuk <ilya.builuk@gmail.com>"]
license = "Apache-2.0"
keywords = ["vrp", "optimization"]
categories = ["algorithms", "science"]
readme = "../README.md"
homepage = "https://github.com/reinterpretcat/vrp"
repository = "https://github.com/reinterpretcat/vrp"
edition = "2018"
description = "A command line interface for VRP solver"

[features]
default = ["csv-format", "hre-format", "scientific-format"]

csv-format = ["csv"]
hre-format = []
scientific-format = ["vrp-scientific"]

[lib]
name = "vrp_cli"
crate-type = ["cdylib", "lib"]

[dependencies]
vrp-core = { path = "../vrp-core", version = "1.9.1" }
vrp-scientific = { path = "../vrp-scientific", version = "1.9.1", optional = true }
vrp-pragmatic = { path = "../vrp-pragmatic", version = "1.9.1" }

csv = { version = "1.1.6", optional = true }
serde_json = "1.0.64"
serde = { version = "1.0.125", features = ["derive"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
clap = "2.33.3"
num_cpus = "1.13.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = { version = "0.2.73", features = ["serde-serialize"] }
js-sys = "0.3.50"
