[package]
name = "vrp-pragmatic"
version = "1.10.1"
authors = ["Ilya Builuk <ilya.builuk@gmail.com>"]
license = "Apache-2.0"
keywords = ["vrp", "optimization"]
categories = ["algorithms", "science"]
readme = "README.md"
homepage = "https://github.com/reinterpretcat/vrp"
repository = "https://github.com/reinterpretcat/vrp"
edition = "2018"
description = "An extension logic for solving rich VRP"

[dependencies]
vrp-core = { path = "../vrp-core", version = "1.10.1" }

serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.64"

chrono = "0.4.19"
rand = "0.8.3"
hashbrown = "0.11.2"

[dev-dependencies]
proptest = "1.0.0"
uuid = { version = "0.8.2", features = ["v4"] }
