[package]
name = "vrp-pragmatic"
version = "1.13.0"
authors = ["Ilya Builuk <ilya.builuk@gmail.com>"]
license = "Apache-2.0"
keywords = ["vrp", "optimization"]
categories = ["algorithms", "science"]
readme = "README.md"
homepage = "https://github.com/reinterpretcat/vrp"
repository = "https://github.com/reinterpretcat/vrp"
edition = "2021"
description = "An extension logic for solving rich VRP"

[dependencies]
vrp-core = { path = "../vrp-core", version = "1.13.0" }

serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.72"

time = { version = "0.3.5", features = ["parsing", "formatting"] }
rand = "0.8.4"
hashbrown = "0.11.2"

[dev-dependencies]
proptest = "1.0.0"
uuid = { version = "0.8.2", features = ["v4"] }
