[package]
name = "vrp-pragmatic"
version = "1.19.1"
authors = ["Ilya Builuk <ilya.builuk@gmail.com>"]
license = "Apache-2.0"
keywords = ["vrp", "optimization"]
categories = ["algorithms", "science"]
readme = "README.md"
homepage = "https://github.com/reinterpretcat/vrp"
repository = "https://github.com/reinterpretcat/vrp"
edition = "2021"
description = "An extension logic for solving rich VRP"

[dependencies]
vrp-core = { path = "../vrp-core", version = "1.19.1" }

serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"

time = { version = "0.3.17", features = ["parsing", "formatting"] }
rand = { version = "0.8.5", features = ["small_rng"] }
hashbrown = "0.13.2"

[dev-dependencies]
proptest = "1.0.0"
uuid = { version = "1.2.2", features = ["v4"] }
