[package]
name = "vrp-core"
version = "1.12.0"
authors = ["Ilya Builuk <ilya.builuk@gmail.com>"]
license = "Apache-2.0"
keywords = ["vrp", "optimization"]
categories = ["algorithms", "science"]
readme = "README.md"
homepage = "https://github.com/reinterpretcat/vrp"
repository = "https://github.com/reinterpretcat/vrp"
edition = "2021"
description = "A core algorithms to solve a Vehicle Routing Problem"

[dependencies]
rayon = "1.5.1"
rand = "0.8.4"
hashbrown = "0.11.2"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
num_cpus = "1.13.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { version = "0.2.3", features = ["js"] }
js-sys = "0.3.55"
