name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Release build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --all-features -- -D warnings
    - name: WebAssembly build
      run: |
        curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
        cd vrp-cli
        wasm-pack build --target web