name: Discovery tests

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'A branch name'
        required: false
        default: 'master'

jobs:
  discovery-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Build and run discovery tests
        run: RUST_BACKTRACE=1 cargo test --release -- --ignored discovery

